namespace Demos.MusicTheory.ChromaticContext.ChromaticNoteIntervalFullyQualified.Providers;

public interface IChromaticIntervalFullyQualifiedProviderFromChromaticIndexSpan
{
    public ChromaticNoteIntervalFullyQualifiedCluster GetIntervals(int chromaticIndexSpan);
}